### ISSUE TITLE
Linux APP

### ISSUE THREAD

**Issue by mathcaapp** [mathcaapp/mathca#8]
Considering the significance of Linux users, we intend to develop a Linux-compatible version of our app during the next months. 

- [ ] Generate base application
- [ ] Code Adaptation and Optimization
- [ ] Dependency Management
- [ ] User Interface (UI) & User Experience (UX) Design
- [ ] Testing and Bug Fixing
- [ ] Documentation and Support
